version: '3'
services:
  app: 
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80' #HTTP Traffic
      - '443:443' #HTTPS Traffic
      - '81:81' #Dashboard Port
    volumes:
      - '/docker/npm/data:/data'
      - '/docker/npm/letsencrypt:/etc/letsencrypt'
